### ISSUE TITLE
Possibility to do mixed model statistics ?

### ISSUE THREAD

**Issue by dhuzard** [ACCLAB/DABEST-python#143]
Hi, thanks a lot for this tool, I love it.
But I'm considering adding my GLMM statistics and would like to know if it is something that could be added easily ?
(I have experimental design with strong 'cage-effect' among my animals, and would like to control for it as a 'random effect' in the GLMM, also in a repeated-measure design experiment).
Thank you very much!

**Comment by adamcc** [comment]
Hi @dhuzard 
Thanks for your kind words. 
We will discuss this in our forthcoming developer meeting.
Also, please feel free to fork the repo and do your own assessment of how hard this will be. 
Cheers

**Comment by adamcc** [comment]
Hi @dhuzard , 

We just discussed this, and decided that its not something that we could easily do at the moment. 

Additional notes from @hwchoi912 
"Thank you for your inquiry, and for your recommendation of incorporating linear mixed effects modeling into the DABEST repertoire. It is unfortunately difficult to reconcile the two worlds mainly because DABEST embodies calculation and visualization of effect sizes and their variability based on bootstrapping. The other challenge there is that random effects reported from mixed effects regression models are predicted values (best unbiased linear predictors, or BLUPS), not statistical estimates. Therefore, bootstrapping will not be applicable for the characterization of the “random effect” distributions, whether it be computed at the cage level or at the individual animal level."

Kind regards, 
Adam
