### ISSUE TITLE
Limitation of paired analysis: Statistics comparing to only one group instead of with each other

### ISSUE THREAD

**Issue by sharahgripable** [ACCLAB/DABEST-python#146]
I am still learning about dabest and not a statistician so please pardon my limited knowledge. 

I am just wondering why are we allowed to only compare to one control for paired data. In repeated measure design we would like to either see the overall effect of groups on the data or comparison with each other.

For example if you have three group repeated measure design (no group is considered 'baseline', I would ideally want to be able to compare between g1-g2, g2-g3, g3-g1. I understand that we can see this visually in the plot, however what troubles me is that in the statistical_tests result it shows either between g1-g2 and g2-g3, not g3-g1. 

In this case how would be report the overall difference between each other (group)? 

Edit: I also tried 
`dabest.load(data=df, x="x", y="y", idx=(('g1', 'g2'), ('g2', 'g3'), ('g1', 'g3'), paired="sequential", id_col='ID').mean_diff`
however it is not allowing me to do that because:

`ValueError: Groups are repeated across tuples, or a tuple has repeated groups in it. Please remove any duplicates and try again.`

**Comment by JAnns98** [comment]
Hi @sharahgripable, apologies this was never responded to. It is our desired design that groups cannot be repeated. Our philosophy is that paired experiments should be focused on comparing test groups to a shared control or looking at the sequential differences (rather than looking for differences between any group combination). 

If one would like to create such plots, it is relatively simple to brute force. For example, by duplicating the g1 group and renaming the duplicate to something else (and then changing the name back in the figure label). 

I will close this thread for now, but feel free to reopen it if there are more questions.
