### ISSUE TITLE
Change range and tick frequency on contrast axis independently from the rawswarm yaxis

### ISSUE THREAD

**Issue by johannesbjork** [ACCLAB/DABEST-python#22]
I am trying to find a way to change breaks/tick frequency on the contrast axis independently from the rawswarm y axis. Either on a single or tiled Gardner-Altman plot.

My first language is `R` so please bear with me. 

```
from scipy.stats import norm

np.random.seed(9999) # Fix the seed so the results are replicable.
pop_size = 10000 # Size of each population.
Ns = 20 # The number of samples taken from each population

# Create populations
pop1 = norm.rvs(loc=3, scale=0.4, size=pop_size)
pop2 = norm.rvs(loc=3.5, scale=0.5, size=pop_size)
pop3 = norm.rvs(loc=2.5, scale=0.6, size=pop_size)
pop4 = norm.rvs(loc=3, scale=0.75, size=pop_size)
pop5 = norm.rvs(loc=3.5, scale=0.75, size=pop_size)
pop6 = norm.rvs(loc=3.25, scale=0.4, size=pop_size)

# Sample from the populations
sampling_kwargs = dict(size=Ns, replace=False)

g1 = np.random.choice(pop1, **sampling_kwargs)
g2 = np.random.choice(pop2, **sampling_kwargs)
g3 = np.random.choice(pop3, **sampling_kwargs)
g4 = np.random.choice(pop4, **sampling_kwargs)
g5 = np.random.choice(pop5, **sampling_kwargs)
g6 = np.random.choice(pop6, **sampling_kwargs)

# Add a `gender` column for coloring the data.
females = np.repeat('Female', Ns/2).tolist()
males = np.repeat('Male', Ns/2).tolist()
gender = females + males

# Add an `id` column for paired data plotting.
# More info below!
id_col = pd.Series(range(1, Ns+1))

# Combine samples and gender into a DataFrame.
df = pd.DataFrame({'Control' : g1,
  'Group 1' : g2,
  'Group 2' : g3,
  'Group 3' : g4,
  'Group 4' : g5,
  'Group 5' : g6,
  'Gender'  : gender,
  'ID'      : id_col
})
```

`f1, r1 = dabest.plot(df, idx=(('Group 2','Group 3'),('Group 4','Group 5')))` 
This produces the plot5 in the dabest tutorial. Let say you want to change the y axis to span some predefined range.

`f2, r2 = dabest.plot(df, idx=(('Group 2','Group 3'),('Group 4','Group 5')),
                              swarm_ylim=(1,6))`
Here we are changing the range of the rawswarm y axis. This also alters the contrast axis. This is my main problem. Given my predefined range on the rawswarm y axis, I want a different range and a higher frequency of ticks on the contrast axis

```
f3, r3 = dabest.plot(df, idx=(('Group 2','Group 3'),('Group 4','Group 5')),
                     swarm_ylim=(1,6))

contrast_axes = f3.axes[2]
contrast_axes.set_ylim(-1,1)
contrast_axes.yaxis.set_major_locator(ticker.MultipleLocator(0.1))
```

While this changes the range and tick frequency of the contrast axis, it also widens the mean difference distribution and messes with the position of the zero and mean difference lines, shifted them upwards. One another thing I don't understand is, when you increase the range of the contrast axis, e.g., by setting `contrast_axes.set_ylim(-3,3)`, the mean difference distribution becomes less stretched, almost as it originally appeared in `f1`.

Any help on the matter would be highly appreciated. 
Thanks.

**Comment by josesho** [comment]
Hi @johannesbjork, firstly thank you for your clear and reproducible example! 

While it is possible (as you have demonstrated) to manually change the contrast axis for a Gardner-Altman plot (`float_contrast=False`), the alignment between the rawdata axis and the contrast axis will be broken. This is why the position of the zero and mean difference lines are misaligned between the axes. 

As such, for a Gardner-Altman plot, setting the `contrast_ylim` option does not do anything in `dabest.plot()`. 

Currently, the way a Gardner-Altman plot is generated is: plot the raw data on the rawdata axis,, plot the bootstrap contrast on the contrast axis, and then _align the contrast axis to the rawdata axis_. Given that both axis are shifted by a linear scalar, I suppose the process could be reversed (set the y-limits for the contrast axis, then align the rawdata axis to it). I don't see such a feature being implemented anytime soon.

If you really want to control the contrast axis y-limits and tick locations, I'd suggest using a Cumming plot, where the bootstrap distributions and effect sizes are plotted below instead of alongside the raw data.

```python
f, r = dabest.plot(df, idx=(('Group 2','Group 3'),('Group 4','Group 5')),
                     float_contrast=False,
                     contrast_ylim=(-1,2)
                    )

contrast_axes = f.axes[2]
contrast_axes.yaxis.set_major_locator(ticker.MultipleLocator(0.5))
contrast_axes.yaxis.set_minor_locator(ticker.MultipleLocator(0.25))
```

![download](https://user-images.githubusercontent.com/12838917/53612280-ab234400-3c0c-11e9-99cd-3d95feba0739.png)

PS Have you taken a look at our R version [dabestr](https://github.com/ACCLAB/dabestr)? You might find it more helpful if you're more familiar with R!

**Comment by johannesbjork** [comment]
Hi Joses,

I did write a reproducible example (I always do).

Cheers,
Johannes

------------------------------------------
Johannes R Björk, PhD
Postdoctoral research fellow
Archie Lab
Department of Biological Sciences
University of Notre Dame, IN, USA
Alt. email: rbjork@nd.edu
Skype: johannesbjork

**Comment by josesho** [comment]
ooops, my bad!
